apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-backend-app
  labels:
    app: harness-backend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: harness-backend-app
  template:
    metadata:
      labels:
        app: harness-backend-app
    spec:
      containers:
      - name: java-server
        # 💡 Harness will replace this image URL (backend)
        image: us-east1-docker.pkg.dev/gp-project-480716/gp-harness-repository-registry/backend-app:22
        ports:
        - containerPort: 8080
        env:
        - name: APP_VERSION
          value: "v1.0.0-Backend"