pipeline:
  name: CD
  identifier: CD
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Deploy to GKE
        identifier: deploy_gke
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: gke-harness-app
          environment:
            environmentRef: dev
            infrastructureDefinitions:
              - identifier: gke_dev
          execution:
            steps:
              - step:
                  type: K8sRollingDeploy
                  name: Rolling Deploy
                  identifier: rolling_deploy
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  type: K8sRollingRollback
                  name: Rollback
                  identifier: rollback
                  spec:
                    pruningEnabled: false
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
