pipeline:
  name: CI
  identifier: CI
  projectIdentifier: default_project
  orgIdentifier: default
  codebase:
    connectorRef: githubharnessconnector
    repoName: harness-gke-lab
    build:
      type: branch
      spec:
        branch: dev
  stages:
    - stage:
        name: Build and Push Images
        identifier: build_push
        type: CI
        spec:
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Check Files
                  identifier: check_files
                  spec:
                    shell: Sh
                    command: |
                      pwd
                      ls -R
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build Backend Image
                  identifier: build_backend
                  spec:
                    connectorRef: gcpharnessregistry
                    repo: us-east1-docker.pkg.dev/gp-project-480716/gp-harness-repository-registry
                    tags:
                      - <+pipeline.sequenceId>
                    dockerfile: apps/backend/Dockerfile
                    context: .
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build Frontend Image
                  identifier: build_frontend
                  spec:
                    connectorRef: gcpharnessregistry
                    repo: us-east1-docker.pkg.dev/gp-project-480716/gp-harness-repository-registry
                    tags:
                      - <+pipeline.sequenceId>
                    dockerfile: apps/frontend/Dockerfile
                    context: .
          cloneCodebase: false
        description: ""
  properties:
    ci:
      codebase:
        connectorRef: githubharnessconnector
        build: <+input>
        sparseCheckout: []
